Generate a fresh host/ key using passwd -r when possible.
git-svn-id: svn+ssh://slccvsl02.prod.quest.corp/opt/svn/rc/vasidmap/trunk@129 d2f197e3-5317-0410-bdde-f57cf7c060d4

diff --git a/vas-samba-config b/vas-samba-config
--- a/vas-samba-config
+++ b/vas-samba-config
@@ -393,6 +393,7 @@ CONFMOD=${VASCONF}.mod
 cp ${VASCONF} ${CONFMOD}
 NEWTEXT=/tmp/newtext$$.tmp
 
+have_pwchgscript=false
 case "$VERSION" in
   3.0.*|3.1.1.39|3.1.1.4[0123456])
     # VAS 3.0.x and 3.1.1.39 thru .46 need the make password permanent
@@ -403,6 +404,7 @@ case "$VERSION" in
     check_and_fix "password-change-script" "${PWDCHGSCRIPT}" "${CONFMOD}" ||
         echo " password-change-script = ${PWDCHGSCRIPT}" >> $NEWTEXT
     check_and_fix "password-change-interval" "30" "${CONFMOD}"
+    have_pwchgscript=true
     ;;
 esac
 
@@ -458,14 +460,22 @@ if [ "$PWDCHANGE" = "yes" ]; then
 
     echo "Renewing the computer account password..."
 
-    #Generate a secret key from the hex form of current key material
-    SECRET='X!'`$VASTOOL ktutil list --keys | 
-        awk 'NR==4{print substr($4,0,16);exit}'`
-    # Change the machine password using vastool
-    (echo "$SECRET"; echo "$SECRET") | ${VASTOOL} -s -u host/ passwd
+    if $have_pwchgscript; then
+	# Generate a new machine secret and set directly.
+	$VASTOOL -u host/ -q passwd -r -o | ${PWDCHGSCRIPT}
+    else
+	# Generate a secret key from the hex form of current key material
+	SECRET='X!'`$VASTOOL ktutil list --keys | 
+	    awk 'NR==4{print substr($4,0,16);exit}'`
+	# Change the machine password using vastool
+	(echo "$SECRET"; echo "$SECRET") | ${VASTOOL} -s -u host/ passwd
+	# Set the new machine password in secrets.tdb
+	echo "$SECRET" | ${PWDCHGSCRIPT}
+    fi
 
-    # Set the new machine password into secrets.tdb
-    echo "$SECRET" | ${PWDCHGSCRIPT}
+    # Test that the join worked ok
+    /opt/quest/bin/net ads testjoin ||
+	echo "** net ads testjoin failed" >&2
 fi
 
 ### Finally restart samba services
