Add RPMDIR detection for redhat. Allows RPMs to be built on redhat.

diff --git a/pkg/rpm/build b/pkg/rpm/build
--- a/pkg/rpm/build
+++ b/pkg/rpm/build
@@ -14,8 +14,12 @@ cd $CURDIR
 if [ -f /etc/debian_version ]; then
 	RPMDIR=/usr/src/rpm
 else
-	echo "Unknown platform, can't set RPMDIR"
-	exit 1
+	if [ -f /etc/redhat-release ]; then
+		RPMDIR=/usr/src/redhat
+	else
+		echo "Unknown platform, can't set RPMDIR"
+		exit 1
+	fi
 fi
 
 cp ../$NAME-$VERSION.tar.gz $RPMDIR/SOURCES
